"""Sachima Private Hermes Runtime Spine — R1 core (local/offline).

The minimal runtime backbone: one ``task_id`` spine, a refs-only Task Event Log
that is the single monotonic ``seq`` authority, a deterministic Status Projection,
a log-derived Task Registry snapshot cache, a static Capability Registry, and a
typed, fail-closed LaunchSpec.

Everything here is pure local/offline Python. Importing this package starts no
subprocess, socket, Docker, daemon, Temporal service/Worker/client, Gateway,
Feishu, or network call, launches no OS process or agent (acpx/npx), and wires no
supervisor execution port (that is R2). Forbidden terms appear only as no-leak
denylist canaries, never as behavior. See
``docs/architecture/private-hermes-runtime-spine-design.md``.
"""

from __future__ import annotations

from .capabilities import (
    CAPABILITY_FIELDS,
    Capability,
    get_capability,
    known_agent_kinds,
)
from .events import (
    ALLOWED_EVENT_BODY_KEYS,
    EVENT_TYPES,
    FORBIDDEN_MARKERS,
    KNOWN_FLAG_KEYS,
    RUNTIME_EVENT_LEAK_DETECTED,
    RUNTIME_INVALID_EVENT,
    RUNTIME_INVALID_LAUNCH_SPEC,
    RUNTIME_INVALID_PROJECTION,
    RUNTIME_INVALID_TASK_ID,
    RUNTIME_INVALID_TASK_RECORD,
    RUNTIME_SEQ_VIOLATION,
    RUNTIME_UNKNOWN_CAPABILITY,
    STABLE_CODES,
    STATUS_VALUES,
    TERMINAL_STATUSES,
    SpineError,
    TaskEvent,
    TaskEventLog,
    build_event_body,
    event_projection,
    safe_error_code,
    safe_role_key,
    safe_task_id,
    scan_for_leak,
    validate_event_body,
    verify_seq_contiguous,
)
from .canary import (
    CANARY_PACKET_TYPE,
    CANARY_REPORT_TYPE,
    CANARY_STABLE_CODES,
    RUNTIME_CANARY_NOT_AUTHORIZED,
    RUNTIME_INVALID_CANARY_PACKET,
    CanaryDryRunReport,
    CanaryRequestPacket,
    build_bounded_canary_packet,
    build_canary_dry_run_report,
    serialize_canary_dry_run_report,
    serialize_canary_request_packet,
    validate_canary_dry_run_report,
    validate_canary_request_packet,
)
from .execution_port import (
    LIVE_SESSION_STATES,
    PORT_STABLE_CODES,
    REAPABLE_SESSION_STATES,
    RUNTIME_INVALID_SESSION,
    SESSION_STATES,
    TERMINAL_SESSION_STATES,
    ExecutionPort,
    LivenessState,
    SessionRef,
    SessionStatus,
    validate_liveness_state,
    validate_session_ref,
    validate_session_status,
)
from .fake_supervisor_port import FakeSupervisorPort
from .agent_run_supervisor_port import (
    LIFECYCLE_SNAPSHOT_TYPE,
    RUNTIME_SUPERVISOR_BACKEND_FAILURE,
    RUNTIME_SUPERVISOR_POLICY_DENIED,
    SUPERVISOR_PORT_STABLE_CODES,
    AgentRunSupervisorBackend,
    AgentRunSupervisorPort,
    DefaultAgentRunSupervisorBackend,
    LifecycleSnapshot,
    validate_lifecycle_snapshot,
)
from .agent_run_supervisor_readonly_smoke import (
    AGENT_RUN_SUPERVISOR_READ_ONLY_SMOKE_APPROVAL_TOKEN,
    READ_ONLY_SMOKE_READINESS_LIMITATION,
    REQUIRED_RUNNER_VERSION,
    SMOKE_STABLE_CODES,
    ReadOnlySmokeFixture,
    ReadOnlySmokeReadinessReport,
    ReadOnlySmokeReadinessRequest,
    ReadOnlySmokeReport,
    assess_read_only_smoke_readiness,
    run_read_only_smoke,
)
from .launch_spec import (
    KNOWN_MODE_FLAGS,
    LaunchSpec,
    build_launch_spec,
    validate_launch_spec,
)
from .live_progress_projection import (
    LIVE_PROGRESS_CORRUPT,
    LIVE_PROGRESS_PROJECTION_TYPE,
    LIVE_PROGRESS_STABLE_CODES,
    LIVE_PROGRESS_UNAVAILABLE,
    OBSERVED_EVENT_STATUSES,
    RUNTIME_INVALID_LIVE_PROGRESS,
    SUPERVISOR_OBSERVED_STATES,
    DefaultLiveProgressReader,
    LiveProgressEventRecord,
    LiveProgressProjection,
    LiveProgressReader,
    build_live_progress_projection,
    serialize_live_progress_projection,
    validate_live_progress_event_record,
    validate_live_progress_projection,
)
from .projection import (
    ALLOWED_PROJECTION_KEYS,
    PROJECTION_TYPE,
    project,
    serialize_projection,
)
from .registry import TaskRecord, TaskRegistry
from .temporal_bridge import (
    BRIDGE_PHASES,
    BRIDGE_STABLE_CODES,
    RUNTIME_INVALID_TEMPORAL_BRIDGE,
    AgentRunActivityInput,
    AgentRunActivityResult,
    HeartbeatPayload,
    TemporalAttachOnlyBridge,
    TemporalWorkflowContract,
    validate_agent_run_activity_input,
    validate_heartbeat_payload,
    validate_workflow_contract,
)
from .permissions import (
    ALLOWED_PERMISSION_ROLES,
    PERMISSION_STABLE_CODES,
    RUNTIME_INVALID_PERMISSION,
    RUNTIME_PERMISSION_ROLE_DENIED,
    PermissionDecision,
    PermissionPolicy,
    PermissionRequest,
    apply_permission_decision,
    request_permission,
    validate_permission_decision,
    validate_permission_request,
    validate_role_policy,
)
from .view_model import (
    RUNTIME_INVALID_VIEW_MODEL,
    VIEW_MODEL_STABLE_CODES,
    VIEW_MODEL_TYPE,
    TaskViewModel,
    build_task_view_model,
    serialize_task_view_model,
    validate_task_view_model,
)
from .agent_run_supervisor_workbench import (
    RUNTIME_INVALID_WORKBENCH_VIEW,
    WORKBENCH_STABLE_CODES,
    WORKBENCH_VIEW_TYPE,
    AgentRunSupervisorWorkbenchView,
    build_agent_run_supervisor_workbench_view,
    serialize_agent_run_supervisor_workbench_view,
    validate_agent_run_supervisor_workbench_view,
)
from .agent_run_supervisor_live_workbench import (
    LIVE_WORKBENCH_STABLE_CODES,
    LIVE_WORKBENCH_VIEW_TYPE,
    RUNTIME_INVALID_LIVE_WORKBENCH_VIEW,
    AgentRunSupervisorLiveWorkbenchView,
    build_agent_run_supervisor_live_workbench_view,
    serialize_agent_run_supervisor_live_workbench_view,
    validate_agent_run_supervisor_live_workbench_view,
)
from .agent_run_supervisor_production_e2e import (
    E2E_BACKEND_FAILURE,
    E2E_INVALID_FIXTURE,
    E2E_INVALID_REPORT,
    E2E_INVARIANT_VIOLATION,
    E2E_LEASE_UNAVAILABLE,
    E2E_REPORT_TYPE,
    E2E_STABLE_CODES,
    E2E_UNEXPECTED_LEAK,
    ProductionE2EFixture,
    ProductionE2EReport,
    run_single_user_production_e2e,
    serialize_production_e2e_report,
    validate_production_e2e_fixture,
    validate_production_e2e_report,
)
from .workspace import (
    RUNTIME_INVALID_WORKSPACE_LEASE,
    RUNTIME_WORKSPACE_LEASE_CONFLICT,
    WORKSPACE_STABLE_CODES,
    WorkspaceLease,
    WorkspaceLeaseStore,
    acquire_workspace_lease,
    reclaim_expired_workspace_lease,
    release_workspace_lease,
    validate_workspace_lease,
)

__all__ = [
    # errors / stable codes
    "SpineError",
    "STABLE_CODES",
    "RUNTIME_INVALID_TASK_ID",
    "RUNTIME_INVALID_EVENT",
    "RUNTIME_SEQ_VIOLATION",
    "RUNTIME_EVENT_LEAK_DETECTED",
    "RUNTIME_INVALID_PROJECTION",
    "RUNTIME_INVALID_TASK_RECORD",
    "RUNTIME_UNKNOWN_CAPABILITY",
    "RUNTIME_INVALID_LAUNCH_SPEC",
    "RUNTIME_INVALID_SESSION",
    "PORT_STABLE_CODES",
    # events / log
    "FORBIDDEN_MARKERS",
    "EVENT_TYPES",
    "STATUS_VALUES",
    "TERMINAL_STATUSES",
    "ALLOWED_EVENT_BODY_KEYS",
    "KNOWN_FLAG_KEYS",
    "TaskEvent",
    "TaskEventLog",
    "build_event_body",
    "validate_event_body",
    "event_projection",
    "verify_seq_contiguous",
    "scan_for_leak",
    "safe_task_id",
    "safe_role_key",
    "safe_error_code",
    # R5 controlled canary / product hardening
    "RUNTIME_INVALID_CANARY_PACKET",
    "RUNTIME_CANARY_NOT_AUTHORIZED",
    "CANARY_STABLE_CODES",
    "CANARY_PACKET_TYPE",
    "CANARY_REPORT_TYPE",
    "CanaryRequestPacket",
    "CanaryDryRunReport",
    "build_bounded_canary_packet",
    "build_canary_dry_run_report",
    "validate_canary_request_packet",
    "validate_canary_dry_run_report",
    "serialize_canary_request_packet",
    "serialize_canary_dry_run_report",
    # execution port
    "SESSION_STATES",
    "LIVE_SESSION_STATES",
    "TERMINAL_SESSION_STATES",
    "REAPABLE_SESSION_STATES",
    "ExecutionPort",
    "SessionRef",
    "LivenessState",
    "SessionStatus",
    "validate_session_ref",
    "validate_liveness_state",
    "validate_session_status",
    "FakeSupervisorPort",
    "RUNTIME_SUPERVISOR_BACKEND_FAILURE",
    "RUNTIME_SUPERVISOR_POLICY_DENIED",
    "SUPERVISOR_PORT_STABLE_CODES",
    "AgentRunSupervisorBackend",
    "AgentRunSupervisorPort",
    "DefaultAgentRunSupervisorBackend",
    # PR3 persistent session lifecycle
    "LIFECYCLE_SNAPSHOT_TYPE",
    "LifecycleSnapshot",
    "validate_lifecycle_snapshot",
    # PR2 host-local read-only smoke harness + readiness probe
    "AGENT_RUN_SUPERVISOR_READ_ONLY_SMOKE_APPROVAL_TOKEN",
    "READ_ONLY_SMOKE_READINESS_LIMITATION",
    "REQUIRED_RUNNER_VERSION",
    "SMOKE_STABLE_CODES",
    "ReadOnlySmokeFixture",
    "ReadOnlySmokeReport",
    "ReadOnlySmokeReadinessRequest",
    "ReadOnlySmokeReadinessReport",
    "run_read_only_smoke",
    "assess_read_only_smoke_readiness",
    # projection
    "PROJECTION_TYPE",
    "ALLOWED_PROJECTION_KEYS",
    "project",
    "serialize_projection",
    # registry
    "TaskRecord",
    "TaskRegistry",
    # temporal attach-only bridge (R3)
    "RUNTIME_INVALID_TEMPORAL_BRIDGE",
    "BRIDGE_STABLE_CODES",
    "BRIDGE_PHASES",
    "HeartbeatPayload",
    "AgentRunActivityInput",
    "AgentRunActivityResult",
    "TemporalWorkflowContract",
    "TemporalAttachOnlyBridge",
    "validate_heartbeat_payload",
    "validate_agent_run_activity_input",
    "validate_workflow_contract",
    # R4 workspace / permission / view model
    "RUNTIME_INVALID_WORKSPACE_LEASE",
    "RUNTIME_WORKSPACE_LEASE_CONFLICT",
    "WORKSPACE_STABLE_CODES",
    "WorkspaceLease",
    "WorkspaceLeaseStore",
    "acquire_workspace_lease",
    "release_workspace_lease",
    "reclaim_expired_workspace_lease",
    "validate_workspace_lease",
    "RUNTIME_INVALID_PERMISSION",
    "RUNTIME_PERMISSION_ROLE_DENIED",
    "PERMISSION_STABLE_CODES",
    "ALLOWED_PERMISSION_ROLES",
    "PermissionPolicy",
    "PermissionRequest",
    "PermissionDecision",
    "request_permission",
    "apply_permission_decision",
    "validate_role_policy",
    "validate_permission_request",
    "validate_permission_decision",
    "RUNTIME_INVALID_VIEW_MODEL",
    "VIEW_MODEL_STABLE_CODES",
    "VIEW_MODEL_TYPE",
    "TaskViewModel",
    "build_task_view_model",
    "validate_task_view_model",
    "serialize_task_view_model",
    # PR4 StatusProjection + task workbench view
    "RUNTIME_INVALID_WORKBENCH_VIEW",
    "WORKBENCH_STABLE_CODES",
    "WORKBENCH_VIEW_TYPE",
    "AgentRunSupervisorWorkbenchView",
    "build_agent_run_supervisor_workbench_view",
    "validate_agent_run_supervisor_workbench_view",
    "serialize_agent_run_supervisor_workbench_view",
    # PR-LS1 ARS live-progress + task workbench composite view
    "RUNTIME_INVALID_LIVE_WORKBENCH_VIEW",
    "LIVE_WORKBENCH_STABLE_CODES",
    "LIVE_WORKBENCH_VIEW_TYPE",
    "AgentRunSupervisorLiveWorkbenchView",
    "build_agent_run_supervisor_live_workbench_view",
    "validate_agent_run_supervisor_live_workbench_view",
    "serialize_agent_run_supervisor_live_workbench_view",
    # PR5 single-user production-shaped E2E
    "E2E_INVALID_FIXTURE",
    "E2E_INVALID_REPORT",
    "E2E_INVARIANT_VIOLATION",
    "E2E_UNEXPECTED_LEAK",
    "E2E_BACKEND_FAILURE",
    "E2E_LEASE_UNAVAILABLE",
    "E2E_STABLE_CODES",
    "E2E_REPORT_TYPE",
    "ProductionE2EFixture",
    "ProductionE2EReport",
    "validate_production_e2e_fixture",
    "validate_production_e2e_report",
    "serialize_production_e2e_report",
    "run_single_user_production_e2e",
    # PR3 live progress safe projection (foreign ARS artifact read-model)
    "RUNTIME_INVALID_LIVE_PROGRESS",
    "LIVE_PROGRESS_UNAVAILABLE",
    "LIVE_PROGRESS_CORRUPT",
    "LIVE_PROGRESS_STABLE_CODES",
    "LIVE_PROGRESS_PROJECTION_TYPE",
    "SUPERVISOR_OBSERVED_STATES",
    "OBSERVED_EVENT_STATUSES",
    "LiveProgressReader",
    "DefaultLiveProgressReader",
    "LiveProgressEventRecord",
    "LiveProgressProjection",
    "build_live_progress_projection",
    "validate_live_progress_projection",
    "validate_live_progress_event_record",
    "serialize_live_progress_projection",
    # capabilities
    "Capability",
    "CAPABILITY_FIELDS",
    "get_capability",
    "known_agent_kinds",
    # launch spec
    "LaunchSpec",
    "KNOWN_MODE_FLAGS",
    "build_launch_spec",
    "validate_launch_spec",
]
