"""Sachima Private Hermes Runtime Spine — R1 core (local/offline).

The minimal runtime backbone: one ``task_id`` spine, a refs-only Task Event Log
that is the single monotonic ``seq`` authority, a deterministic Status Projection,
a log-derived Task Registry snapshot cache, a static Capability Registry, and a
typed, fail-closed LaunchSpec.

Everything here is pure local/offline Python. Importing this package starts no
subprocess, socket, Docker, daemon, Temporal service/Worker/client, Gateway,
Feishu, or network call, launches no OS process or agent (acpx/npx), and wires no
supervisor execution port (that is R2). Forbidden terms appear only as no-leak
denylist canaries, never as behavior. See
``docs/architecture/private-hermes-runtime-spine-design.md``.
"""

from __future__ import annotations

from .capabilities import (
    CAPABILITY_FIELDS,
    Capability,
    get_capability,
    known_agent_kinds,
)
from .events import (
    ALLOWED_EVENT_BODY_KEYS,
    EVENT_TYPES,
    FORBIDDEN_MARKERS,
    KNOWN_FLAG_KEYS,
    RUNTIME_EVENT_LEAK_DETECTED,
    RUNTIME_INVALID_EVENT,
    RUNTIME_INVALID_LAUNCH_SPEC,
    RUNTIME_INVALID_PROJECTION,
    RUNTIME_INVALID_TASK_ID,
    RUNTIME_INVALID_TASK_RECORD,
    RUNTIME_SEQ_VIOLATION,
    RUNTIME_UNKNOWN_CAPABILITY,
    STABLE_CODES,
    STATUS_VALUES,
    TERMINAL_STATUSES,
    SpineError,
    TaskEvent,
    TaskEventLog,
    build_event_body,
    event_projection,
    safe_error_code,
    safe_role_key,
    safe_task_id,
    scan_for_leak,
    validate_event_body,
    verify_seq_contiguous,
)
from .execution_port import (
    LIVE_SESSION_STATES,
    PORT_STABLE_CODES,
    REAPABLE_SESSION_STATES,
    RUNTIME_INVALID_SESSION,
    SESSION_STATES,
    TERMINAL_SESSION_STATES,
    ExecutionPort,
    LivenessState,
    SessionRef,
    SessionStatus,
    validate_liveness_state,
    validate_session_ref,
    validate_session_status,
)
from .fake_supervisor_port import FakeSupervisorPort
from .agent_run_supervisor_port import (
    LIFECYCLE_SNAPSHOT_TYPE,
    RUNTIME_SUPERVISOR_BACKEND_FAILURE,
    RUNTIME_SUPERVISOR_POLICY_DENIED,
    SUPERVISOR_PORT_STABLE_CODES,
    AgentRunSupervisorBackend,
    AgentRunSupervisorPort,
    DefaultAgentRunSupervisorBackend,
    LifecycleSnapshot,
    validate_lifecycle_snapshot,
)
from .supervisor_turn_backend import (
    RUNTIME_INVALID_SUPERVISOR_TURN,
    SOURCE_KIND_ARSD_RUN,
    SOURCE_KIND_ARTIFACT_FILE,
    SUPERVISOR_SOURCE_KINDS,
    SUPERVISOR_TURN_STABLE_CODES,
    SUPERVISOR_TURN_STATUSES,
    DispatchedSupervisorTurn,
    SupervisorTurnBackend,
    SupervisorTurnResult,
    TurnSourceSink,
    derive_turn_ref,
    serialize_supervisor_turn_result,
    validate_supervisor_turn_backend,
    validate_supervisor_turn_result,
    validate_turn_source_sink,
)
from .agent_run_supervisor_turn_dispatcher import (
    RUNTIME_ARS_TURN_FAILED,
    RUNTIME_INVALID_TURN_DISPATCH,
    RUNTIME_TURN_DISPATCH_BUSY,
    TURN_DISPATCH_STABLE_CODES,
    TURN_KINDS,
    AgentRunSupervisorTurnDispatcher,
    TurnDispatchOutcome,
    TurnDispatchRequest,
    validate_turn_dispatch_outcome,
    validate_turn_dispatch_request,
)
from .agent_run_supervisor_execution_binding import (
    AgentRunSupervisorExecutionBinding,
    bind_arsd_execution,
    prompt_resolver_from_payload_resolver,
)
from .arsd_run_binding_ledger import (
    ARSD_BINDING_ACCEPTED,
    ARSD_BINDING_LEDGER_TYPE,
    ARSD_BINDING_PENDING,
    ARSD_BINDING_STABLE_CODES,
    ARSD_BINDING_STATES,
    RUNTIME_ARSD_BINDING_CONFLICT,
    RUNTIME_INVALID_ARSD_BINDING,
    ArsdRunBinding,
    ArsdRunBindingLedger,
    derive_arsd_binding_key,
    derive_run_ref,
)
from .arsd_supervisor_backend import (
    ARSD_BACKEND_STABLE_CODES,
    ARSD_TERMINAL_TO_NEUTRAL_STATUS,
    ArsdLiveProgressReader,
    ArsdSupervisorBackend,
    derive_arsd_backend_handle,
    map_arsd_terminal_to_neutral,
)
from .arsd_socket_contract import (
    ARSD_MAX_FRAME_BYTES,
    ARSD_MAX_PROMPT_BYTES,
    ARSD_REQUIRED_API_VERSION,
    ARSD_SPEC_SCHEMA_VERSION,
    ARSD_STABLE_CODES,
    ARSD_SUPERVISOR_CONFIG_TYPE,
    RUNTIME_ARSD_BUSY,
    RUNTIME_ARSD_DISABLED,
    RUNTIME_ARSD_IDEMPOTENCY_CONFLICT,
    RUNTIME_ARSD_INTERNAL,
    RUNTIME_ARSD_INVALID_REQUEST,
    RUNTIME_ARSD_POLICY_DENIED,
    RUNTIME_ARSD_PROTOCOL_VIOLATION,
    RUNTIME_ARSD_SHUTTING_DOWN,
    RUNTIME_ARSD_SUBMISSION_INDETERMINATE,
    RUNTIME_ARSD_UNAVAILABLE,
    RUNTIME_ARSD_UNKNOWN_TARGET,
    RUNTIME_ARSD_VERSION_MISMATCH,
    RUNTIME_INVALID_ARSD_CONFIG,
    ArsdClientFacade,
    ArsdRunEventsPage,
    ArsdServerInfo,
    ArsdSubmitAccepted,
    ArsdSupervisorConfig,
    DefaultArsdClientFacade,
    arsd_submit_payload_digest,
    build_arsd_submit_payload,
    derive_arsd_request_id,
    map_arsd_client_error_code,
    require_enabled_arsd_supervisor_config,
    validate_arsd_run_events_page,
    validate_arsd_server_info,
    validate_arsd_submit_result,
    validate_arsd_supervisor_config,
)
from .launch_spec import (
    KNOWN_MODE_FLAGS,
    LaunchSpec,
    build_launch_spec,
    validate_launch_spec,
)
from .projection import (
    ALLOWED_PROJECTION_KEYS,
    PROJECTION_TYPE,
    project,
    serialize_projection,
)
from .registry import TaskRecord, TaskRegistry
from .temporal_bridge import (
    BRIDGE_PHASES,
    BRIDGE_STABLE_CODES,
    RUNTIME_INVALID_TEMPORAL_BRIDGE,
    AgentRunActivityInput,
    AgentRunActivityResult,
    HeartbeatPayload,
    TemporalAttachOnlyBridge,
    TemporalWorkflowContract,
    validate_agent_run_activity_input,
    validate_heartbeat_payload,
    validate_workflow_contract,
)
from .permissions import (
    ALLOWED_PERMISSION_ROLES,
    PERMISSION_STABLE_CODES,
    RUNTIME_INVALID_PERMISSION,
    RUNTIME_PERMISSION_ROLE_DENIED,
    PermissionDecision,
    PermissionPolicy,
    PermissionRequest,
    apply_permission_decision,
    request_permission,
    validate_permission_decision,
    validate_permission_request,
    validate_role_policy,
)
from .view_model import (
    RUNTIME_INVALID_VIEW_MODEL,
    VIEW_MODEL_STABLE_CODES,
    VIEW_MODEL_TYPE,
    TaskViewModel,
    build_task_view_model,
    serialize_task_view_model,
    validate_task_view_model,
)
from .workspace import (
    RUNTIME_INVALID_WORKSPACE_LEASE,
    RUNTIME_WORKSPACE_LEASE_CONFLICT,
    WORKSPACE_STABLE_CODES,
    WorkspaceLease,
    WorkspaceLeaseStore,
    acquire_workspace_lease,
    reclaim_expired_workspace_lease,
    release_workspace_lease,
    validate_workspace_lease,
)

__all__ = [
    # errors / stable codes
    "SpineError",
    "STABLE_CODES",
    "RUNTIME_INVALID_TASK_ID",
    "RUNTIME_INVALID_EVENT",
    "RUNTIME_SEQ_VIOLATION",
    "RUNTIME_EVENT_LEAK_DETECTED",
    "RUNTIME_INVALID_PROJECTION",
    "RUNTIME_INVALID_TASK_RECORD",
    "RUNTIME_UNKNOWN_CAPABILITY",
    "RUNTIME_INVALID_LAUNCH_SPEC",
    "RUNTIME_INVALID_SESSION",
    "PORT_STABLE_CODES",
    # events / log
    "FORBIDDEN_MARKERS",
    "EVENT_TYPES",
    "STATUS_VALUES",
    "TERMINAL_STATUSES",
    "ALLOWED_EVENT_BODY_KEYS",
    "KNOWN_FLAG_KEYS",
    "TaskEvent",
    "TaskEventLog",
    "build_event_body",
    "validate_event_body",
    "event_projection",
    "verify_seq_contiguous",
    "scan_for_leak",
    "safe_task_id",
    "safe_role_key",
    "safe_error_code",
    # execution port
    "SESSION_STATES",
    "LIVE_SESSION_STATES",
    "TERMINAL_SESSION_STATES",
    "REAPABLE_SESSION_STATES",
    "ExecutionPort",
    "SessionRef",
    "LivenessState",
    "SessionStatus",
    "validate_session_ref",
    "validate_liveness_state",
    "validate_session_status",
    "FakeSupervisorPort",
    "RUNTIME_SUPERVISOR_BACKEND_FAILURE",
    "RUNTIME_SUPERVISOR_POLICY_DENIED",
    "SUPERVISOR_PORT_STABLE_CODES",
    "AgentRunSupervisorBackend",
    "AgentRunSupervisorPort",
    "DefaultAgentRunSupervisorBackend",
    # PR3 persistent session lifecycle
    "LIFECYCLE_SNAPSHOT_TYPE",
    "LifecycleSnapshot",
    "validate_lifecycle_snapshot",
    # ARS-INT socket contract / turn dispatcher / execution binding
    "ARSD_MAX_FRAME_BYTES",
    "ARSD_MAX_PROMPT_BYTES",
    "ARSD_REQUIRED_API_VERSION",
    "ARSD_SPEC_SCHEMA_VERSION",
    "ARSD_STABLE_CODES",
    "ARSD_SUPERVISOR_CONFIG_TYPE",
    "RUNTIME_ARSD_BUSY",
    "RUNTIME_ARSD_DISABLED",
    "RUNTIME_ARSD_IDEMPOTENCY_CONFLICT",
    "RUNTIME_ARSD_INTERNAL",
    "RUNTIME_ARSD_INVALID_REQUEST",
    "RUNTIME_ARSD_POLICY_DENIED",
    "RUNTIME_ARSD_PROTOCOL_VIOLATION",
    "RUNTIME_ARSD_SHUTTING_DOWN",
    "RUNTIME_ARSD_SUBMISSION_INDETERMINATE",
    "RUNTIME_ARSD_UNAVAILABLE",
    "RUNTIME_ARSD_UNKNOWN_TARGET",
    "RUNTIME_ARSD_VERSION_MISMATCH",
    "RUNTIME_INVALID_ARSD_CONFIG",
    "ARSD_BACKEND_STABLE_CODES",
    "ARSD_TERMINAL_TO_NEUTRAL_STATUS",
    "ArsdLiveProgressReader",
    "ArsdSupervisorBackend",
    "derive_arsd_backend_handle",
    "map_arsd_terminal_to_neutral",
    "ArsdClientFacade",
    "ArsdRunEventsPage",
    "ArsdServerInfo",
    "ArsdSubmitAccepted",
    "ArsdSupervisorConfig",
    "DefaultArsdClientFacade",
    "arsd_submit_payload_digest",
    "build_arsd_submit_payload",
    "derive_arsd_request_id",
    "map_arsd_client_error_code",
    "require_enabled_arsd_supervisor_config",
    "validate_arsd_run_events_page",
    "validate_arsd_server_info",
    "validate_arsd_submit_result",
    "validate_arsd_supervisor_config",
    # ARS 0.7.6 P2 durable private Run/Session binding ledger
    "ARSD_BINDING_ACCEPTED",
    "ARSD_BINDING_LEDGER_TYPE",
    "ARSD_BINDING_PENDING",
    "ARSD_BINDING_STABLE_CODES",
    "ARSD_BINDING_STATES",
    "RUNTIME_ARSD_BINDING_CONFLICT",
    "RUNTIME_INVALID_ARSD_BINDING",
    "ArsdRunBinding",
    "ArsdRunBindingLedger",
    "derive_arsd_binding_key",
    "derive_run_ref",
    # ARS 0.7.6 P3 neutral validated turn backend contract
    "RUNTIME_INVALID_SUPERVISOR_TURN",
    "SOURCE_KIND_ARSD_RUN",
    "SOURCE_KIND_ARTIFACT_FILE",
    "SUPERVISOR_SOURCE_KINDS",
    "SUPERVISOR_TURN_STABLE_CODES",
    "SUPERVISOR_TURN_STATUSES",
    "DispatchedSupervisorTurn",
    "SupervisorTurnBackend",
    "SupervisorTurnResult",
    "TurnSourceSink",
    "serialize_supervisor_turn_result",
    "validate_supervisor_turn_backend",
    "validate_supervisor_turn_result",
    "validate_turn_source_sink",
    "RUNTIME_ARS_TURN_FAILED",
    "RUNTIME_INVALID_TURN_DISPATCH",
    "RUNTIME_TURN_DISPATCH_BUSY",
    "TURN_DISPATCH_STABLE_CODES",
    "TURN_KINDS",
    "AgentRunSupervisorTurnDispatcher",
    "TurnDispatchOutcome",
    "TurnDispatchRequest",
    "derive_turn_ref",
    "validate_turn_dispatch_outcome",
    "validate_turn_dispatch_request",
    "AgentRunSupervisorExecutionBinding",
    "bind_arsd_execution",
    "prompt_resolver_from_payload_resolver",
    # projection
    "PROJECTION_TYPE",
    "ALLOWED_PROJECTION_KEYS",
    "project",
    "serialize_projection",
    # registry
    "TaskRecord",
    "TaskRegistry",
    # temporal attach-only bridge (R3)
    "RUNTIME_INVALID_TEMPORAL_BRIDGE",
    "BRIDGE_STABLE_CODES",
    "BRIDGE_PHASES",
    "HeartbeatPayload",
    "AgentRunActivityInput",
    "AgentRunActivityResult",
    "TemporalWorkflowContract",
    "TemporalAttachOnlyBridge",
    "validate_heartbeat_payload",
    "validate_agent_run_activity_input",
    "validate_workflow_contract",
    # R4 workspace / permission / view model
    "RUNTIME_INVALID_WORKSPACE_LEASE",
    "RUNTIME_WORKSPACE_LEASE_CONFLICT",
    "WORKSPACE_STABLE_CODES",
    "WorkspaceLease",
    "WorkspaceLeaseStore",
    "acquire_workspace_lease",
    "release_workspace_lease",
    "reclaim_expired_workspace_lease",
    "validate_workspace_lease",
    "RUNTIME_INVALID_PERMISSION",
    "RUNTIME_PERMISSION_ROLE_DENIED",
    "PERMISSION_STABLE_CODES",
    "ALLOWED_PERMISSION_ROLES",
    "PermissionPolicy",
    "PermissionRequest",
    "PermissionDecision",
    "request_permission",
    "apply_permission_decision",
    "validate_role_policy",
    "validate_permission_request",
    "validate_permission_decision",
    "RUNTIME_INVALID_VIEW_MODEL",
    "VIEW_MODEL_STABLE_CODES",
    "VIEW_MODEL_TYPE",
    "TaskViewModel",
    "build_task_view_model",
    "validate_task_view_model",
    "serialize_task_view_model",
    # capabilities
    "Capability",
    "CAPABILITY_FIELDS",
    "get_capability",
    "known_agent_kinds",
    # launch spec
    "LaunchSpec",
    "KNOWN_MODE_FLAGS",
    "build_launch_spec",
    "validate_launch_spec",
]
