"""Sachima Private Hermes Runtime Spine — R1 core (local/offline).

The minimal runtime backbone: one ``task_id`` spine, a refs-only Task Event Log
that is the single monotonic ``seq`` authority, a deterministic Status Projection,
a log-derived Task Registry snapshot cache, a static Capability Registry, and a
typed, fail-closed LaunchSpec.

Everything here is pure local/offline Python. Importing this package starts no
subprocess, socket, Docker, daemon, Temporal service/Worker/client, Gateway,
Feishu, or network call, launches no OS process or agent (acpx/npx), and wires no
supervisor execution port (that is R2). Forbidden terms appear only as no-leak
denylist canaries, never as behavior. See
``docs/architecture/private-hermes-runtime-spine-design.md``.
"""

from __future__ import annotations

from .capabilities import (
    CAPABILITY_FIELDS,
    Capability,
    get_capability,
    known_agent_kinds,
)
from .events import (
    ALLOWED_EVENT_BODY_KEYS,
    EVENT_TYPES,
    FORBIDDEN_MARKERS,
    KNOWN_FLAG_KEYS,
    RUNTIME_EVENT_LEAK_DETECTED,
    RUNTIME_INVALID_EVENT,
    RUNTIME_INVALID_LAUNCH_SPEC,
    RUNTIME_INVALID_PROJECTION,
    RUNTIME_INVALID_TASK_ID,
    RUNTIME_INVALID_TASK_RECORD,
    RUNTIME_SEQ_VIOLATION,
    RUNTIME_UNKNOWN_CAPABILITY,
    STABLE_CODES,
    STATUS_VALUES,
    TERMINAL_STATUSES,
    SpineError,
    TaskEvent,
    TaskEventLog,
    build_event_body,
    event_projection,
    safe_error_code,
    safe_role_key,
    safe_task_id,
    scan_for_leak,
    validate_event_body,
    verify_seq_contiguous,
)
from .canary import (
    CANARY_PACKET_TYPE,
    CANARY_REPORT_TYPE,
    CANARY_STABLE_CODES,
    RUNTIME_CANARY_NOT_AUTHORIZED,
    RUNTIME_INVALID_CANARY_PACKET,
    CanaryDryRunReport,
    CanaryRequestPacket,
    build_bounded_canary_packet,
    build_canary_dry_run_report,
    serialize_canary_dry_run_report,
    serialize_canary_request_packet,
    validate_canary_dry_run_report,
    validate_canary_request_packet,
)
from .execution_port import (
    LIVE_SESSION_STATES,
    PORT_STABLE_CODES,
    REAPABLE_SESSION_STATES,
    RUNTIME_INVALID_SESSION,
    SESSION_STATES,
    TERMINAL_SESSION_STATES,
    ExecutionPort,
    LivenessState,
    SessionRef,
    SessionStatus,
    validate_liveness_state,
    validate_session_ref,
    validate_session_status,
)
from .fake_supervisor_port import FakeSupervisorPort
from .agent_run_supervisor_port import (
    LIFECYCLE_SNAPSHOT_TYPE,
    RUNTIME_SUPERVISOR_BACKEND_FAILURE,
    RUNTIME_SUPERVISOR_POLICY_DENIED,
    SUPERVISOR_PORT_STABLE_CODES,
    AgentRunSupervisorBackend,
    AgentRunSupervisorPort,
    DefaultAgentRunSupervisorBackend,
    LifecycleSnapshot,
    validate_lifecycle_snapshot,
)
from .agent_run_supervisor_library_backend import (
    ARS_LIBRARY_CONFIG_TYPE,
    ARS_LIBRARY_STABLE_CODES,
    RUNTIME_ARS_LIBRARY_DISABLED,
    RUNTIME_ARS_LIBRARY_UNAVAILABLE,
    RUNTIME_INVALID_ARS_LIBRARY_CONFIG,
    AgentRunSupervisorLibraryBackend,
    AgentRunSupervisorLibraryConfig,
    LibraryTurnResult,
    LibraryUnavailableError,
    derive_ars_session_id,
    derive_backend_handle,
    validate_agent_run_supervisor_library_config,
)
from .agent_run_supervisor_turn_dispatcher import (
    RUNTIME_ARS_TURN_FAILED,
    RUNTIME_INVALID_TURN_DISPATCH,
    RUNTIME_TURN_DISPATCH_BUSY,
    TURN_DISPATCH_STABLE_CODES,
    TURN_KINDS,
    AgentRunSupervisorTurnDispatcher,
    TurnDispatchOutcome,
    TurnDispatchRequest,
    derive_turn_ref,
    validate_turn_dispatch_outcome,
    validate_turn_dispatch_request,
)
from .agent_run_supervisor_execution_binding import (
    AgentRunSupervisorExecutionBinding,
    bind_agent_run_supervisor_execution,
)
from .arsd_socket_contract import (
    ARSD_MAX_FRAME_BYTES,
    ARSD_MAX_PROMPT_BYTES,
    ARSD_REQUIRED_API_VERSION,
    ARSD_SPEC_SCHEMA_VERSION,
    ARSD_STABLE_CODES,
    ARSD_SUPERVISOR_CONFIG_TYPE,
    RUNTIME_ARSD_BUSY,
    RUNTIME_ARSD_DISABLED,
    RUNTIME_ARSD_IDEMPOTENCY_CONFLICT,
    RUNTIME_ARSD_INTERNAL,
    RUNTIME_ARSD_INVALID_REQUEST,
    RUNTIME_ARSD_POLICY_DENIED,
    RUNTIME_ARSD_PROTOCOL_VIOLATION,
    RUNTIME_ARSD_SHUTTING_DOWN,
    RUNTIME_ARSD_SUBMISSION_INDETERMINATE,
    RUNTIME_ARSD_UNAVAILABLE,
    RUNTIME_ARSD_UNKNOWN_TARGET,
    RUNTIME_ARSD_VERSION_MISMATCH,
    RUNTIME_INVALID_ARSD_CONFIG,
    ArsdClientFacade,
    ArsdRunEventsPage,
    ArsdServerInfo,
    ArsdSubmitAccepted,
    ArsdSupervisorConfig,
    DefaultArsdClientFacade,
    arsd_submit_payload_digest,
    build_arsd_submit_payload,
    derive_arsd_request_id,
    map_arsd_client_error_code,
    require_enabled_arsd_supervisor_config,
    validate_arsd_run_events_page,
    validate_arsd_server_info,
    validate_arsd_submit_result,
    validate_arsd_supervisor_config,
)
from .agent_run_supervisor_readonly_smoke import (
    AGENT_RUN_SUPERVISOR_READ_ONLY_SMOKE_APPROVAL_TOKEN,
    READ_ONLY_SMOKE_READINESS_LIMITATION,
    REQUIRED_RUNNER_VERSION,
    SMOKE_STABLE_CODES,
    ReadOnlySmokeFixture,
    ReadOnlySmokeReadinessReport,
    ReadOnlySmokeReadinessRequest,
    ReadOnlySmokeReport,
    assess_read_only_smoke_readiness,
    run_read_only_smoke,
)
from .launch_spec import (
    KNOWN_MODE_FLAGS,
    LaunchSpec,
    build_launch_spec,
    validate_launch_spec,
)
from .live_progress_projection import (
    LIVE_PROGRESS_CORRUPT,
    LIVE_PROGRESS_PROJECTION_TYPE,
    LIVE_PROGRESS_STABLE_CODES,
    LIVE_PROGRESS_UNAVAILABLE,
    OBSERVED_EVENT_STATUSES,
    RUNTIME_INVALID_LIVE_PROGRESS,
    SUPERVISOR_OBSERVED_STATES,
    DefaultLiveProgressReader,
    LiveProgressEventRecord,
    LiveProgressProjection,
    LiveProgressReader,
    build_live_progress_projection,
    serialize_live_progress_projection,
    validate_live_progress_event_record,
    validate_live_progress_projection,
)
from .projection import (
    ALLOWED_PROJECTION_KEYS,
    PROJECTION_TYPE,
    project,
    serialize_projection,
)
from .registry import TaskRecord, TaskRegistry
from .temporal_bridge import (
    BRIDGE_PHASES,
    BRIDGE_STABLE_CODES,
    RUNTIME_INVALID_TEMPORAL_BRIDGE,
    AgentRunActivityInput,
    AgentRunActivityResult,
    HeartbeatPayload,
    TemporalAttachOnlyBridge,
    TemporalWorkflowContract,
    validate_agent_run_activity_input,
    validate_heartbeat_payload,
    validate_workflow_contract,
)
from .permissions import (
    ALLOWED_PERMISSION_ROLES,
    PERMISSION_STABLE_CODES,
    RUNTIME_INVALID_PERMISSION,
    RUNTIME_PERMISSION_ROLE_DENIED,
    PermissionDecision,
    PermissionPolicy,
    PermissionRequest,
    apply_permission_decision,
    request_permission,
    validate_permission_decision,
    validate_permission_request,
    validate_role_policy,
)
from .view_model import (
    RUNTIME_INVALID_VIEW_MODEL,
    VIEW_MODEL_STABLE_CODES,
    VIEW_MODEL_TYPE,
    TaskViewModel,
    build_task_view_model,
    serialize_task_view_model,
    validate_task_view_model,
)
from .agent_run_supervisor_workbench import (
    RUNTIME_INVALID_WORKBENCH_VIEW,
    WORKBENCH_STABLE_CODES,
    WORKBENCH_VIEW_TYPE,
    AgentRunSupervisorWorkbenchView,
    build_agent_run_supervisor_workbench_view,
    serialize_agent_run_supervisor_workbench_view,
    validate_agent_run_supervisor_workbench_view,
)
from .agent_run_supervisor_live_workbench import (
    LIVE_WORKBENCH_STABLE_CODES,
    LIVE_WORKBENCH_VIEW_TYPE,
    RUNTIME_INVALID_LIVE_WORKBENCH_VIEW,
    AgentRunSupervisorLiveWorkbenchView,
    build_agent_run_supervisor_live_workbench_view,
    serialize_agent_run_supervisor_live_workbench_view,
    validate_agent_run_supervisor_live_workbench_view,
)
from .live_progress_sources import (
    LIVE_PROGRESS_SOURCE_STABLE_CODES,
    LIVE_PROGRESS_SOURCE_TYPE,
    RUNTIME_INVALID_LIVE_PROGRESS_SOURCE,
    LiveProgressSource,
    LiveProgressSourceBindings,
    ResolvedLiveProgressSource,
    build_agent_run_supervisor_live_workbench_from_source,
    serialize_live_progress_source,
    validate_live_progress_source,
)
from .agent_run_supervisor_live_progress_smoke import (
    LIVE_PROGRESS_SMOKE_REPORT_TYPE,
    LIVE_PROGRESS_SMOKE_STABLE_CODES,
    RUNTIME_INVALID_LIVE_PROGRESS_SMOKE,
    SMOKE_OUTCOMES,
    LiveProgressSmokeReport,
    build_live_progress_smoke_report,
    serialize_live_progress_smoke_report,
    smoke_live_progress_projection,
    smoke_live_progress_report,
    smoke_live_workbench_view,
    validate_live_progress_smoke_report,
)
from .live_progress_query import (
    APPROVED_QUERY_SURFACES,
    HERMES_INTERNAL_QUERY_SURFACE,
    LIVE_PROGRESS_QUERY_GATE_TYPE,
    LIVE_PROGRESS_QUERY_STABLE_CODES,
    LOCAL_OFFLINE_QUERY_SURFACE,
    RUNTIME_INVALID_LIVE_PROGRESS_QUERY,
    RUNTIME_LIVE_PROGRESS_QUERY_DISABLED,
    LiveProgressQueryActivationGate,
    LiveProgressQueryService,
    build_live_progress_query_activation_gate,
    hermes_internal_query_gate,
    local_offline_query_gate,
    query_task_live_progress,
    validate_live_progress_query_activation_gate,
)
from .live_progress_display import (
    LIVE_PROGRESS_DISPLAY_STABLE_CODES,
    LIVE_PROGRESS_DISPLAY_TYPE,
    RUNTIME_INVALID_LIVE_PROGRESS_DISPLAY,
    LiveProgressDisplay,
    LiveProgressDisplayService,
    display_task_live_progress,
    render_live_progress_display,
    serialize_live_progress_display,
    validate_live_progress_display,
)
from .agent_run_supervisor_production_e2e import (
    E2E_BACKEND_FAILURE,
    E2E_INVALID_FIXTURE,
    E2E_INVALID_REPORT,
    E2E_INVARIANT_VIOLATION,
    E2E_LEASE_UNAVAILABLE,
    E2E_REPORT_TYPE,
    E2E_STABLE_CODES,
    E2E_UNEXPECTED_LEAK,
    ProductionE2EFixture,
    ProductionE2EReport,
    run_single_user_production_e2e,
    serialize_production_e2e_report,
    validate_production_e2e_fixture,
    validate_production_e2e_report,
)
from .workspace import (
    RUNTIME_INVALID_WORKSPACE_LEASE,
    RUNTIME_WORKSPACE_LEASE_CONFLICT,
    WORKSPACE_STABLE_CODES,
    WorkspaceLease,
    WorkspaceLeaseStore,
    acquire_workspace_lease,
    reclaim_expired_workspace_lease,
    release_workspace_lease,
    validate_workspace_lease,
)

__all__ = [
    # errors / stable codes
    "SpineError",
    "STABLE_CODES",
    "RUNTIME_INVALID_TASK_ID",
    "RUNTIME_INVALID_EVENT",
    "RUNTIME_SEQ_VIOLATION",
    "RUNTIME_EVENT_LEAK_DETECTED",
    "RUNTIME_INVALID_PROJECTION",
    "RUNTIME_INVALID_TASK_RECORD",
    "RUNTIME_UNKNOWN_CAPABILITY",
    "RUNTIME_INVALID_LAUNCH_SPEC",
    "RUNTIME_INVALID_SESSION",
    "PORT_STABLE_CODES",
    # events / log
    "FORBIDDEN_MARKERS",
    "EVENT_TYPES",
    "STATUS_VALUES",
    "TERMINAL_STATUSES",
    "ALLOWED_EVENT_BODY_KEYS",
    "KNOWN_FLAG_KEYS",
    "TaskEvent",
    "TaskEventLog",
    "build_event_body",
    "validate_event_body",
    "event_projection",
    "verify_seq_contiguous",
    "scan_for_leak",
    "safe_task_id",
    "safe_role_key",
    "safe_error_code",
    # R5 controlled canary / product hardening
    "RUNTIME_INVALID_CANARY_PACKET",
    "RUNTIME_CANARY_NOT_AUTHORIZED",
    "CANARY_STABLE_CODES",
    "CANARY_PACKET_TYPE",
    "CANARY_REPORT_TYPE",
    "CanaryRequestPacket",
    "CanaryDryRunReport",
    "build_bounded_canary_packet",
    "build_canary_dry_run_report",
    "validate_canary_request_packet",
    "validate_canary_dry_run_report",
    "serialize_canary_request_packet",
    "serialize_canary_dry_run_report",
    # execution port
    "SESSION_STATES",
    "LIVE_SESSION_STATES",
    "TERMINAL_SESSION_STATES",
    "REAPABLE_SESSION_STATES",
    "ExecutionPort",
    "SessionRef",
    "LivenessState",
    "SessionStatus",
    "validate_session_ref",
    "validate_liveness_state",
    "validate_session_status",
    "FakeSupervisorPort",
    "RUNTIME_SUPERVISOR_BACKEND_FAILURE",
    "RUNTIME_SUPERVISOR_POLICY_DENIED",
    "SUPERVISOR_PORT_STABLE_CODES",
    "AgentRunSupervisorBackend",
    "AgentRunSupervisorPort",
    "DefaultAgentRunSupervisorBackend",
    # PR3 persistent session lifecycle
    "LIFECYCLE_SNAPSHOT_TYPE",
    "LifecycleSnapshot",
    "validate_lifecycle_snapshot",
    # ARS-INT formal library backend / turn dispatcher / execution binding
    "ARS_LIBRARY_CONFIG_TYPE",
    "ARSD_MAX_FRAME_BYTES",
    "ARSD_MAX_PROMPT_BYTES",
    "ARSD_REQUIRED_API_VERSION",
    "ARSD_SPEC_SCHEMA_VERSION",
    "ARSD_STABLE_CODES",
    "ARSD_SUPERVISOR_CONFIG_TYPE",
    "RUNTIME_ARSD_BUSY",
    "RUNTIME_ARSD_DISABLED",
    "RUNTIME_ARSD_IDEMPOTENCY_CONFLICT",
    "RUNTIME_ARSD_INTERNAL",
    "RUNTIME_ARSD_INVALID_REQUEST",
    "RUNTIME_ARSD_POLICY_DENIED",
    "RUNTIME_ARSD_PROTOCOL_VIOLATION",
    "RUNTIME_ARSD_SHUTTING_DOWN",
    "RUNTIME_ARSD_SUBMISSION_INDETERMINATE",
    "RUNTIME_ARSD_UNAVAILABLE",
    "RUNTIME_ARSD_UNKNOWN_TARGET",
    "RUNTIME_ARSD_VERSION_MISMATCH",
    "RUNTIME_INVALID_ARSD_CONFIG",
    "ArsdClientFacade",
    "ArsdRunEventsPage",
    "ArsdServerInfo",
    "ArsdSubmitAccepted",
    "ArsdSupervisorConfig",
    "DefaultArsdClientFacade",
    "arsd_submit_payload_digest",
    "build_arsd_submit_payload",
    "derive_arsd_request_id",
    "map_arsd_client_error_code",
    "require_enabled_arsd_supervisor_config",
    "validate_arsd_run_events_page",
    "validate_arsd_server_info",
    "validate_arsd_submit_result",
    "validate_arsd_supervisor_config",
    "ARS_LIBRARY_STABLE_CODES",
    "RUNTIME_ARS_LIBRARY_DISABLED",
    "RUNTIME_ARS_LIBRARY_UNAVAILABLE",
    "RUNTIME_INVALID_ARS_LIBRARY_CONFIG",
    "AgentRunSupervisorLibraryBackend",
    "AgentRunSupervisorLibraryConfig",
    "LibraryTurnResult",
    "LibraryUnavailableError",
    "derive_ars_session_id",
    "derive_backend_handle",
    "validate_agent_run_supervisor_library_config",
    "RUNTIME_ARS_TURN_FAILED",
    "RUNTIME_INVALID_TURN_DISPATCH",
    "RUNTIME_TURN_DISPATCH_BUSY",
    "TURN_DISPATCH_STABLE_CODES",
    "TURN_KINDS",
    "AgentRunSupervisorTurnDispatcher",
    "TurnDispatchOutcome",
    "TurnDispatchRequest",
    "derive_turn_ref",
    "validate_turn_dispatch_outcome",
    "validate_turn_dispatch_request",
    "AgentRunSupervisorExecutionBinding",
    "bind_agent_run_supervisor_execution",
    # PR2 host-local read-only smoke harness + readiness probe
    "AGENT_RUN_SUPERVISOR_READ_ONLY_SMOKE_APPROVAL_TOKEN",
    "READ_ONLY_SMOKE_READINESS_LIMITATION",
    "REQUIRED_RUNNER_VERSION",
    "SMOKE_STABLE_CODES",
    "ReadOnlySmokeFixture",
    "ReadOnlySmokeReport",
    "ReadOnlySmokeReadinessRequest",
    "ReadOnlySmokeReadinessReport",
    "run_read_only_smoke",
    "assess_read_only_smoke_readiness",
    # projection
    "PROJECTION_TYPE",
    "ALLOWED_PROJECTION_KEYS",
    "project",
    "serialize_projection",
    # registry
    "TaskRecord",
    "TaskRegistry",
    # temporal attach-only bridge (R3)
    "RUNTIME_INVALID_TEMPORAL_BRIDGE",
    "BRIDGE_STABLE_CODES",
    "BRIDGE_PHASES",
    "HeartbeatPayload",
    "AgentRunActivityInput",
    "AgentRunActivityResult",
    "TemporalWorkflowContract",
    "TemporalAttachOnlyBridge",
    "validate_heartbeat_payload",
    "validate_agent_run_activity_input",
    "validate_workflow_contract",
    # R4 workspace / permission / view model
    "RUNTIME_INVALID_WORKSPACE_LEASE",
    "RUNTIME_WORKSPACE_LEASE_CONFLICT",
    "WORKSPACE_STABLE_CODES",
    "WorkspaceLease",
    "WorkspaceLeaseStore",
    "acquire_workspace_lease",
    "release_workspace_lease",
    "reclaim_expired_workspace_lease",
    "validate_workspace_lease",
    "RUNTIME_INVALID_PERMISSION",
    "RUNTIME_PERMISSION_ROLE_DENIED",
    "PERMISSION_STABLE_CODES",
    "ALLOWED_PERMISSION_ROLES",
    "PermissionPolicy",
    "PermissionRequest",
    "PermissionDecision",
    "request_permission",
    "apply_permission_decision",
    "validate_role_policy",
    "validate_permission_request",
    "validate_permission_decision",
    "RUNTIME_INVALID_VIEW_MODEL",
    "VIEW_MODEL_STABLE_CODES",
    "VIEW_MODEL_TYPE",
    "TaskViewModel",
    "build_task_view_model",
    "validate_task_view_model",
    "serialize_task_view_model",
    # PR4 StatusProjection + task workbench view
    "RUNTIME_INVALID_WORKBENCH_VIEW",
    "WORKBENCH_STABLE_CODES",
    "WORKBENCH_VIEW_TYPE",
    "AgentRunSupervisorWorkbenchView",
    "build_agent_run_supervisor_workbench_view",
    "validate_agent_run_supervisor_workbench_view",
    "serialize_agent_run_supervisor_workbench_view",
    # PR-LS1 ARS live-progress + task workbench composite view
    "RUNTIME_INVALID_LIVE_WORKBENCH_VIEW",
    "LIVE_WORKBENCH_STABLE_CODES",
    "LIVE_WORKBENCH_VIEW_TYPE",
    "AgentRunSupervisorLiveWorkbenchView",
    "build_agent_run_supervisor_live_workbench_view",
    "validate_agent_run_supervisor_live_workbench_view",
    "serialize_agent_run_supervisor_live_workbench_view",
    # PR-LS2 host-owned live-progress source binding
    "RUNTIME_INVALID_LIVE_PROGRESS_SOURCE",
    "LIVE_PROGRESS_SOURCE_STABLE_CODES",
    "LIVE_PROGRESS_SOURCE_TYPE",
    "LiveProgressSource",
    "ResolvedLiveProgressSource",
    "LiveProgressSourceBindings",
    "build_agent_run_supervisor_live_workbench_from_source",
    "validate_live_progress_source",
    "serialize_live_progress_source",
    # PR-LS3 agent-run-supervisor caller-API compatibility smoke
    "RUNTIME_INVALID_LIVE_PROGRESS_SMOKE",
    "LIVE_PROGRESS_SMOKE_STABLE_CODES",
    "LIVE_PROGRESS_SMOKE_REPORT_TYPE",
    "SMOKE_OUTCOMES",
    "LiveProgressSmokeReport",
    "smoke_live_progress_projection",
    "smoke_live_workbench_view",
    "smoke_live_progress_report",
    "build_live_progress_smoke_report",
    "validate_live_progress_smoke_report",
    "serialize_live_progress_smoke_report",
    # PR-LS4-A default-off runtime/query activation gate
    "RUNTIME_INVALID_LIVE_PROGRESS_QUERY",
    "RUNTIME_LIVE_PROGRESS_QUERY_DISABLED",
    "LIVE_PROGRESS_QUERY_STABLE_CODES",
    "LIVE_PROGRESS_QUERY_GATE_TYPE",
    "LOCAL_OFFLINE_QUERY_SURFACE",
    "HERMES_INTERNAL_QUERY_SURFACE",
    "APPROVED_QUERY_SURFACES",
    "LiveProgressQueryActivationGate",
    "LiveProgressQueryService",
    "query_task_live_progress",
    "build_live_progress_query_activation_gate",
    "local_offline_query_gate",
    "hermes_internal_query_gate",
    "validate_live_progress_query_activation_gate",
    # PR-LS4-B default-off live-progress display renderer
    "RUNTIME_INVALID_LIVE_PROGRESS_DISPLAY",
    "LIVE_PROGRESS_DISPLAY_STABLE_CODES",
    "LIVE_PROGRESS_DISPLAY_TYPE",
    "LiveProgressDisplay",
    "LiveProgressDisplayService",
    "render_live_progress_display",
    "display_task_live_progress",
    "validate_live_progress_display",
    "serialize_live_progress_display",
    # PR5 single-user production-shaped E2E
    "E2E_INVALID_FIXTURE",
    "E2E_INVALID_REPORT",
    "E2E_INVARIANT_VIOLATION",
    "E2E_UNEXPECTED_LEAK",
    "E2E_BACKEND_FAILURE",
    "E2E_LEASE_UNAVAILABLE",
    "E2E_STABLE_CODES",
    "E2E_REPORT_TYPE",
    "ProductionE2EFixture",
    "ProductionE2EReport",
    "validate_production_e2e_fixture",
    "validate_production_e2e_report",
    "serialize_production_e2e_report",
    "run_single_user_production_e2e",
    # PR3 live progress safe projection (foreign ARS artifact read-model)
    "RUNTIME_INVALID_LIVE_PROGRESS",
    "LIVE_PROGRESS_UNAVAILABLE",
    "LIVE_PROGRESS_CORRUPT",
    "LIVE_PROGRESS_STABLE_CODES",
    "LIVE_PROGRESS_PROJECTION_TYPE",
    "SUPERVISOR_OBSERVED_STATES",
    "OBSERVED_EVENT_STATUSES",
    "LiveProgressReader",
    "DefaultLiveProgressReader",
    "LiveProgressEventRecord",
    "LiveProgressProjection",
    "build_live_progress_projection",
    "validate_live_progress_projection",
    "validate_live_progress_event_record",
    "serialize_live_progress_projection",
    # capabilities
    "Capability",
    "CAPABILITY_FIELDS",
    "get_capability",
    "known_agent_kinds",
    # launch spec
    "LaunchSpec",
    "KNOWN_MODE_FLAGS",
    "build_launch_spec",
    "validate_launch_spec",
]
