from __future__ import annotations

import json
from pathlib import Path

from tools import sync_roadmap_status


SNAPSHOT = {
    "repository": "jovijovi/sachima",
    "base_branch": "release/sachima",
    "base_head": "abc123",
    "base_remote": "sachima",
    "ahead": 0,
    "behind": 0,
    "open_pr_count": 1,
    "open_prs": [
        {
            "number": 42,
            "title": "docs: sync roadmap",
            "headRefName": "docs/status-sync",
            "baseRefName": "release/sachima",
            "url": "https://github.com/jovijovi/sachima/pull/42",
        }
    ],
    "latest_merged_prs": [
        {
            "number": 41,
            "title": "feat: previous phase",
            "mergedAt": "2026-06-14T00:00:00Z",
            "mergeCommit": {"oid": "def456"},
            "url": "https://github.com/jovijovi/sachima/pull/41",
        }
    ],
}


def _json_payload_from_block(block: str) -> dict:
    lines = block.splitlines()
    start = lines.index("```json") + 1
    end = lines.index("```")
    return json.loads("\n".join(lines[start:end]))


def test_render_status_block_is_machine_owned_and_json_parsable() -> None:
    block = sync_roadmap_status.render_status_block(SNAPSHOT)

    assert sync_roadmap_status.START_MARKER in block
    assert sync_roadmap_status.END_MARKER in block
    assert "Generated by `tools/sync_roadmap_status.py`; do not edit manually." in block
    assert "evidence only; it does not grant approvals" in block

    payload = _json_payload_from_block(block)
    assert payload["repository"] == "jovijovi/sachima"
    assert payload["base_branch"] == "release/sachima"
    assert payload["base_head"] == "abc123"
    assert payload["open_pr_count"] == 1
    assert payload["latest_merged_prs"][0]["mergeCommit"]["oid"] == "def456"


def test_sync_document_inserts_block_after_intro_when_missing() -> None:
    original = "# Sachima Roadmap Current Status\n\n> Living dashboard.\n\n```text\nlast_updated: old\n```\n"

    updated, changed = sync_roadmap_status.sync_document(original, SNAPSHOT)

    assert changed is True
    assert updated.startswith("# Sachima Roadmap Current Status\n\n> Living dashboard.\n\n")
    assert sync_roadmap_status.START_MARKER in updated
    assert updated.index(sync_roadmap_status.END_MARKER) < updated.index("```text")


def test_sync_document_replaces_only_machine_owned_block() -> None:
    first, changed = sync_roadmap_status.sync_document("# T\n\nbody\n", SNAPSHOT)
    assert changed is True

    next_snapshot = dict(SNAPSHOT)
    next_snapshot["base_head"] = "new789"
    second, changed = sync_roadmap_status.sync_document(first, next_snapshot)

    assert changed is True
    assert "new789" in second
    assert "abc123" not in second
    assert second.count(sync_roadmap_status.START_MARKER) == 1
    assert second.count(sync_roadmap_status.END_MARKER) == 1
    assert "body" in second


def test_check_file_reports_stale_then_clean(tmp_path: Path) -> None:
    status_file = tmp_path / "current-status.md"
    status_file.write_text("# T\n\nbody\n", encoding="utf-8")

    assert sync_roadmap_status.check_file(status_file, SNAPSHOT) is False
    sync_roadmap_status.write_file(status_file, SNAPSHOT)
    assert sync_roadmap_status.check_file(status_file, SNAPSHOT) is True
