from __future__ import annotations

from pathlib import Path

from tools import sync_roadmap_status


LEGACY_BLOCK = """# Sachima Roadmap Current Status

Dashboard intro.

## Machine-owned dynamic status

<!-- sachima-status-sync:start -->
> Generated by old sync.

```json
{"base_head": "abc123", "open_pr_count": 1}
```
<!-- sachima-status-sync:end -->

## Next allowed work

Keep this section.
"""


def test_dashboard_without_machine_block_is_clean(tmp_path: Path) -> None:
    status_file = tmp_path / "current-status.md"
    status_file.write_text("# Current Status\n\nTask board only.\n", encoding="utf-8")

    assert sync_roadmap_status.check_file(status_file) is True
    assert sync_roadmap_status.write_file(status_file) is False


def test_strip_legacy_machine_block_preserves_human_sections() -> None:
    updated, changed = sync_roadmap_status.strip_legacy_machine_block(LEGACY_BLOCK)

    assert changed is True
    assert sync_roadmap_status.START_MARKER not in updated
    assert sync_roadmap_status.END_MARKER not in updated
    assert sync_roadmap_status.LEGACY_HEADING not in updated
    assert "Dashboard intro." in updated
    assert "## Next allowed work" in updated
    assert "base_head" not in updated
    assert "open_pr_count" not in updated


def test_check_file_reports_legacy_then_write_removes_it(tmp_path: Path) -> None:
    status_file = tmp_path / "current-status.md"
    status_file.write_text(LEGACY_BLOCK, encoding="utf-8")

    assert sync_roadmap_status.check_file(status_file) is False
    assert sync_roadmap_status.write_file(status_file) is True
    assert sync_roadmap_status.check_file(status_file) is True


def test_print_mode_documents_no_rendering(capsys) -> None:
    exit_code = sync_roadmap_status.main(["--print"])

    assert exit_code == 0
    assert "no machine-owned git/GitHub block is rendered" in capsys.readouterr().out
