#!/usr/bin/env python3
"""Synchronize the machine-owned dynamic block in roadmap/current-status.md.

The script deliberately owns only the text between START_MARKER and END_MARKER.
Everything outside that block remains human-authored governance meaning.
"""
from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
from pathlib import Path
from typing import Any, Sequence

START_MARKER = "<!-- sachima-status-sync:start -->"
END_MARKER = "<!-- sachima-status-sync:end -->"
DEFAULT_STATUS_FILE = Path("docs/roadmap/current-status.md")
DEFAULT_REPOSITORY = "jovijovi/sachima"
DEFAULT_BASE_BRANCH = "release/sachima"


class StatusSyncError(RuntimeError):
    """Raised when the status document cannot be safely synchronized."""


def render_status_block(snapshot: dict[str, Any]) -> str:
    """Render the generated status block from a normalized snapshot."""
    payload = _normalized_snapshot(snapshot)
    body = json.dumps(payload, indent=2, sort_keys=True)
    return (
        "## Machine-owned dynamic status\n\n"
        f"{START_MARKER}\n"
        "> Generated by `tools/sync_roadmap_status.py`; do not edit manually.\n"
        "> Source of truth: git/GitHub. This block is evidence only; it does not grant approvals.\n\n"
        "```json\n"
        f"{body}\n"
        "```\n"
        f"{END_MARKER}\n"
    )


def sync_document(document: str, snapshot: dict[str, Any]) -> tuple[str, bool]:
    """Return document text with exactly one fresh machine-owned block."""
    block = render_status_block(snapshot)
    if START_MARKER in document or END_MARKER in document:
        updated = _replace_existing_block(document, block)
    else:
        updated = _insert_new_block(document, block)
    return updated, updated != document


def check_file(path: Path, snapshot: dict[str, Any]) -> bool:
    """Return True when the file already contains the expected generated block."""
    original = path.read_text(encoding="utf-8")
    updated, changed = sync_document(original, snapshot)
    return not changed and updated == original


def write_file(path: Path, snapshot: dict[str, Any]) -> bool:
    """Write a fresh generated block. Return True if the file changed."""
    original = path.read_text(encoding="utf-8")
    updated, changed = sync_document(original, snapshot)
    if changed:
        path.write_text(updated, encoding="utf-8")
    return changed


def collect_snapshot(
    *,
    repository: str = DEFAULT_REPOSITORY,
    base_branch: str = DEFAULT_BASE_BRANCH,
    base_remote: str = "origin",
    cwd: Path | None = None,
) -> dict[str, Any]:
    """Collect dynamic git/GitHub truth for the generated block.

    This is read-only: it runs git and gh query commands only. Tests should pass
    --snapshot-json and exercise rendering/sync behavior without network access.
    """
    workdir = cwd or Path.cwd()
    upstream_ref = f"{base_remote}/{base_branch}"
    base_head = _ref_head(upstream_ref, workdir)
    open_prs = _gh_json(
        [
            "gh",
            "pr",
            "list",
            "--repo",
            repository,
            "--base",
            base_branch,
            "--state",
            "open",
            "--json",
            "number,title,headRefName,baseRefName,url,isDraft,mergeStateStatus",
        ],
        cwd=workdir,
    )
    latest_merged_prs = _gh_json(
        [
            "gh",
            "pr",
            "list",
            "--repo",
            repository,
            "--base",
            base_branch,
            "--state",
            "merged",
            "--limit",
            "5",
            "--json",
            "number,title,headRefName,baseRefName,url,mergedAt,mergeCommit",
        ],
        cwd=workdir,
    )
    return {
        "repository": repository,
        "base_branch": base_branch,
        "base_head": base_head,
        "open_pr_count": len(open_prs),
        "open_prs": open_prs,
        "latest_merged_prs": latest_merged_prs,
        "scope_note": "machine dynamic status only; approvals and phase meaning remain human-authored outside this block",
    }


def load_snapshot(path: Path | None, *, repository: str, base_branch: str, base_remote: str) -> dict[str, Any]:
    if path is None:
        return collect_snapshot(
            repository=repository,
            base_branch=base_branch,
            base_remote=base_remote,
        )
    payload = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(payload, dict):
        raise StatusSyncError("snapshot JSON must be an object")
    return payload


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--file", type=Path, default=DEFAULT_STATUS_FILE)
    parser.add_argument("--snapshot-json", type=Path, default=None)
    parser.add_argument("--repo", default=os.environ.get("GITHUB_REPOSITORY", DEFAULT_REPOSITORY))
    parser.add_argument("--base-branch", default=os.environ.get("GITHUB_REF_NAME", DEFAULT_BASE_BRANCH))
    parser.add_argument("--base-remote", default="origin")
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--check", action="store_true", help="fail if the generated block is stale")
    mode.add_argument("--write", action="store_true", help="rewrite the generated block if stale")
    mode.add_argument("--print", action="store_true", help="print the generated block")
    args = parser.parse_args(argv)

    try:
        snapshot = load_snapshot(
            args.snapshot_json,
            repository=args.repo,
            base_branch=args.base_branch,
            base_remote=args.base_remote,
        )
        if args.print:
            print(render_status_block(snapshot), end="")
            return 0
        if args.check:
            if check_file(args.file, snapshot):
                print(f"{args.file}: machine status block is up to date")
                return 0
            print(f"{args.file}: machine status block is stale; run with --write", file=sys.stderr)
            return 1
        changed = write_file(args.file, snapshot)
        print(f"{args.file}: {'updated' if changed else 'already up to date'}")
        return 0
    except (OSError, StatusSyncError, subprocess.CalledProcessError, json.JSONDecodeError) as exc:
        print(f"status sync failed: {_safe_error(exc)}", file=sys.stderr)
        return 2


def _normalized_snapshot(snapshot: dict[str, Any]) -> dict[str, Any]:
    """Return a JSON-stable object without mutating caller data."""
    return json.loads(json.dumps(snapshot, sort_keys=True))


def _replace_existing_block(document: str, block: str) -> str:
    start = document.find(START_MARKER)
    end = document.find(END_MARKER)
    if start == -1 or end == -1 or end < start:
        raise StatusSyncError("status sync markers are malformed")
    block_start = document.rfind("## Machine-owned dynamic status", 0, start)
    if block_start == -1:
        block_start = _line_start(document, start)
    end_line = document.find("\n", end)
    block_end = len(document) if end_line == -1 else end_line + 1
    before = document[:block_start].rstrip() + "\n\n"
    after = document[block_end:].lstrip("\n")
    separator = "\n" if after else ""
    return before + block + separator + after


def _insert_new_block(document: str, block: str) -> str:
    insertion = _metadata_fence_index(document)
    if insertion is None:
        return document.rstrip() + "\n\n" + block
    before = document[:insertion].rstrip() + "\n\n"
    after = document[insertion:].lstrip("\n")
    return before + block + "\n" + after


def _metadata_fence_index(document: str) -> int | None:
    offset = 0
    for line in document.splitlines(keepends=True):
        if line.startswith("```"):
            return offset
        offset += len(line)
    return None


def _line_start(document: str, index: int) -> int:
    previous = document.rfind("\n", 0, index)
    return 0 if previous == -1 else previous + 1


def _ref_head(ref: str, cwd: Path) -> str:
    try:
        return _run_text(["git", "rev-parse", ref], cwd=cwd)
    except subprocess.CalledProcessError:
        return _run_text(["git", "rev-parse", "HEAD"], cwd=cwd)


def _current_branch(cwd: Path) -> str:
    branch = _run_text(["git", "branch", "--show-current"], cwd=cwd)
    return branch or "DETACHED"


def _ahead_behind(upstream_ref: str, cwd: Path) -> tuple[int | None, int | None]:
    try:
        output = _run_text(["git", "rev-list", "--left-right", "--count", f"{upstream_ref}...HEAD"], cwd=cwd)
    except subprocess.CalledProcessError:
        return None, None
    left, right = output.split()
    return int(right), int(left)


def _run_text(command: Sequence[str], *, cwd: Path) -> str:
    result = subprocess.run(
        list(command),
        cwd=cwd,
        check=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
    )
    return result.stdout.strip()


def _gh_json(command: Sequence[str], *, cwd: Path) -> list[dict[str, Any]]:
    text = _run_text(command, cwd=cwd)
    payload = json.loads(text)
    if not isinstance(payload, list):
        raise StatusSyncError("gh JSON response must be a list")
    for item in payload:
        if not isinstance(item, dict):
            raise StatusSyncError("gh JSON list items must be objects")
    return payload


def _safe_error(exc: BaseException) -> str:
    if isinstance(exc, subprocess.CalledProcessError):
        return f"command failed with exit {exc.returncode}: {' '.join(exc.cmd)}"
    return str(exc).splitlines()[0][:200]


if __name__ == "__main__":
    raise SystemExit(main())
